### ISSUE TITLE
Long Article Link lists should be truncated

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#365]
As illustrated by the large number of links added by a recent user of the site, both the view at article/show and the article/edit view would benefit from truncating theee long lists with a link to 'view all lnks'

How does wikipedia deal with this?
How do we decide which links to show above the fold?
How do we display to full list?

**Comment by trystant** [comment]
Wikipedia articles have footnotes, which are not quite the same as links
here, since the links may not relate to any of the text sections on the
article.

I think that a gallery of links may serve us better than just a plain list
at the bottom. In addition, I think that we should show when the link has
been added to the article.

**Comment by trystant** [comment]
so if there are less than 10 links, how does "show more" and "show less" pan out? It doesn't seem like that link would be needed in that place.

**Comment by campgurus** [comment]
yes.  I will fix that first and then see if we still have a problem.

**Comment by campgurus** [comment]
This is on production. Closing.
