### ISSUE TITLE
History page fixes

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#698]
History page currently includes ip address of editors. This should be removed.  Also 'changeset' is no longer the appropriate term. Also, "Event_id" is unnecessary here.

**Comment by campgurus** [comment]
fixed on production

**Comment by trystant** [comment]
Hey, when something is considered "fixed" or "closed", let's describe in
detail what was done, in order to make it very explicitly clear.

I think that that would be helpful.



On Mon, Jul 11, 2016 at 1:03 AM, campgurus <notifications@github.com> wrote:

> fixed on production
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BOWiki/BOW/issues/698#issuecomment-231642781>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAA0xVAqUPMm8PhUTiELyZiErzSa5jIwks5qUc6TgaJpZM4JI4vC>
> .
>



-- 

Mark Nyonmark@grandkru.com

blog.grandkru.com

github.com/trystant
