### ISSUE TITLE
Git branches need to be cleaned up

### ISSUE THREAD

**Issue by trystant** [BOWiki/BOW#83]
@campgurus, @parcheesy 
Taking a look at the git branches on the system, there are multiple situations where there git branches numbered 'feature2'.

In particular, there's: 
````
remotes/origin/cloudfront_2
remotes/origin/image_optimize_2
remotes/origin/messagese3
remotes/origin/analytics2
````

These should be removed. Also, let's try to avoid creating branches unless absolutely necessary.

**Comment by trystant** [comment]
@campgurus 

Which of these duplicate branches are no longer needed?
```
remotes/origin/analytics
remotes/origin/analytics2
remotes/origin/map_moving
remotes/origin/milestones
remotes/origin/milestones2
remotes/origin/map_moving2
```

**Comment by trystant** [comment]
Actually, this is the full list of branches on origin. How many of these can we remove?

```
remotes/heroku-staging/article_form_fix
  remotes/heroku-staging/article_layout
  remotes/heroku-staging/gallery
  remotes/heroku-staging/map_moving
  remotes/heroku-staging/master
  remotes/heroku-staging/split_gem
  remotes/heroku/master
  remotes/origin/115_mailbox_redirect
  remotes/origin/116_javascript_lab
  remotes/origin/209_fix_for_nil_value
  remotes/origin/215_work_in_progress
  remotes/origin/85_edit_buried_too_low
  remotes/origin/add_followers_page
  remotes/origin/add_homeless
  remotes/origin/agency_show
  remotes/origin/al_message
  remotes/origin/analytics
  remotes/origin/analytics2
  remotes/origin/article_form_fix
  remotes/origin/article_layout
  remotes/origin/article_show_mods
  remotes/origin/blurbs
  remotes/origin/carrierwave_optimizer
  remotes/origin/clarfying_article_edit_form
  remotes/origin/cloudfront_2
  remotes/origin/comments
  remotes/origin/conversation_layout
  remotes/origin/edit_form_tooltips
  remotes/origin/fix_friendly_id
  remotes/origin/friendly_id
  remotes/origin/gallery
  remotes/origin/geocode_fix
  remotes/origin/image_optimize_2
  remotes/origin/index_scroll_buttons
  remotes/origin/mailboxer_fixes
  remotes/origin/mailchimp
  remotes/origin/map_moving
  remotes/origin/map_moving2
  remotes/origin/master
  remotes/origin/messagese3
  remotes/origin/metamagic
  remotes/origin/milestones
  remotes/origin/milestones2
  remotes/origin/minor_view_fixes
  remotes/origin/moving_map
  remotes/origin/name_change
  remotes/origin/new_master
  remotes/origin/new_scroll
  remotes/origin/new_split
  remotes/origin/old_master
  remotes/origin/profile_page_fixes
  remotes/origin/rebased_moving_map
  remotes/origin/recaptcha
  remotes/origin/refactored_articles_controller
  remotes/origin/render_blocking_assets
  remotes/origin/revert-28-al_message
  remotes/origin/set_config_vars
  remotes/origin/site_analytics
  remotes/origin/sitemap
  remotes/origin/split
  remotes/origin/split_gem
  remotes/origin/state_filter
  remotes/origin/subheaders
  remotes/origin/taggable
  remotes/origin/temp-master
  remotes/origin/un_storytime
  remotes/origin/user_profile
  remotes/origin/victims_model
```

**Comment by campgurus** [comment]
Here are the ones I believe still have unmerged non-duplicative work on them worth saving:

remotes/origin/master (main branch should not be deleted)
remotes/origin/215_work_in_progress
remotes/origin/blurbs (allowing editor to enter blurb to populate history and email updates)
remotes/origin/conversation_layout (moving delete conversation button)
remotes/origin/fix_friendly_id (attempting to have url pull slug from subjects model)
remotes/origin/geocode_fix (attempting to include state.name in geocoding)
remotes/origin/new_scroll (js scroll buttons using old front page layout)
remotes/origin/profile_page_fixes (issue #116)
remotes/origin/recaptcha (attempting to use recaptcha for signup)
remotes/origin/site_analytics (includes rudimentary analytics page with graphs of site visitors, etc)
remotes/origin/split_gem (allows a/b testing, including results page, requires redis on server)
remotes/origin/taggable (attempts to add tagging to article model, tagging may not be what we want since we may not want user created tags)

**Comment by trystant** [comment]
I think that this can be closed for the time being.
