### ISSUE TITLE
Add clearer error message to create agency form

### ISSUE THREAD

**Issue by campgurus** [BOWiki/BOW#853]
Error message says to fix errors below, but it is not clear what field it refers to.

**Comment by trystant** [comment]
So here is the screenshot that I got for the new agencies page:
![screenshot 2017-04-02 at 4 53 08 am](https://cloud.githubusercontent.com/assets/13509/24585776/54abfb80-1760-11e7-9ce3-6b24c228edcf.png)

Since the only validation on agencies is the following:
```
class Agency < ActiveRecord::Base
...

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :state_id, presence: true
```

It makes sense that the name would be highlighted. At the same time, there doesn't seem to be an error message for the state id, which could cause some confusion.

**Comment by rlgreen91** [comment]
@trystant Please put an asterisk next to the state dropdown as well to indicate it's required.

**Comment by campgurus** [comment]
i am surprised rails did not add the asterisk automatically based on the presence validation...

**Comment by IsaacBell** [comment]
We can add a notifier at the top as well to increase clarity. Screenshot for example: 

![screenshot 2017-05-19 at 1 15 53 pm](https://cloud.githubusercontent.com/assets/2613157/26261086/66ada77a-3c95-11e7-939b-52354a30e4f9.png)

**Comment by trystant** [comment]
@IsaacBell updating the 'message' part of the validation, you're saying?

**Comment by IsaacBell** [comment]
@trystant that too, but in this screenshot the errors are listed at the top ("2 errors prohibited this article from being saved") in addition to being highlighted red in their respective fields.

Could use some style cleanup on the error box as well, but I wanted to throw the idea out first.

**Comment by trystant** [comment]
I like where this is going. I say full speed ahead

**Comment by rlgreen91** [comment]
In the error box, please put a colon after the field name.  So it looks like "Name: Agency names must be unique.  This agency already exists." for example.

Also, for the name message, it might be better to say something like this:
"Name: An agency with this name already exists and can be found <u>here</u>.  If you want to create a new agency, it must have a unique name."
The underline is meant to indicate that it's a link - it would be nice to link to the existing agency's page, so that if the user is looking to edit the agency, they can just click that and go straight to the page.  Of course, I'm assuming that someone gets to the page with the sole intention of adding a new agency - if they're doing this in the process of some larger goal, like adding a new case, then we might change the behavior.

Also, in the state message, it might be better to say something like this:
"State: You must specify the state in which the incident occurred."

**Comment by rlgreen91** [comment]
It appears that this issue is addressed in a merged PR.
